// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dycsblwhwguwprgnmpfq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR5Y3NibHdod2d1d3ByZ25tcGZxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEyODUyOTIsImV4cCI6MjA1Njg2MTI5Mn0.ayl5vljJYdt1L-wKOgLbHjeHElsQytnGRF9nAbd5N7Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);